# This is a basic workflow to help you get started with Actions
name: Flutter Analyze and Build CI (Pull Request)

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
      - run: |
          flutter --disable-analytics
          flutter config --no-analytics
          flutter pub get
        name: flutter pub get (and disable analytics)
      - run: flutter analyze
      - run: flutter build apk --debug --dart-define=beta=true --dart-define=debug_features=true
      - uses: actions/upload-artifact@v3
        with:
          name: BuiltAPK-Beta-PR
          path: "build/app/outputs/flutter-apk/app-debug.apk"
          retention-days: 14
